CoStudyContentManagement/Models/ErrorViewModel.cs
using System;

namespace CoStudyContentManagement.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CoStudyContentManagement/Controllers/CommentController.cs
using Microsoft.AspNetCore.Mvc;

namespace CoStudyContentManagement.Controllers
{
    [Route("[controller]")]
    public class CommentController : Controller
    {
        [Route("all")]
        public IActionResult GetAll()
        {
            ViewBag.GetAllComment = "nav-active";
            return View();
        }

        [Route("detail")]
        public IActionResult GetById([FromQuery] string commentId)
        {
            ViewBag.commentId = commentId;
            return View();
        }
    }
}

CoStudyContentManagement/Controllers/FieldController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoStudyContentManagement.Controllers
{
    [Route("[controller]")]
    public class FieldController : Controller
    {
        [Route("all")]
        public IActionResult GetAllField()
        {
            ViewBag.GetAllField = "nav-active";
            return View();
        }
    }
}

CoStudyContentManagement/Controllers/FieldGroupController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoStudyContentManagement.Controllers
{
    [Route("[controller]")]
    public class FieldGroupController : Controller
    {
        [Route("all")]
        public IActionResult GetAll()
        {
            ViewBag.GetAllFieldGroup = "nav-active";
            return View();
        }
    }
}

CoStudyContentManagement/Controllers/HomeController.cs
using CoStudyContentManagement.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace CoStudyContentManagement.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Login()
        {
            return View();
        }

        public IActionResult Index()
        {
            ViewBag.Index = "nav-active";
            return View();
        }

        public IActionResult Privacy()
        {
            ViewBag.Privacy = "nav-active";
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CoStudyContentManagement/Controllers/LevelController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoStudyContentManagement.Controllers
{
    [Route("[controller]")]
    public class LevelController : Controller
    {
        [Route("all")]
        public IActionResult GetAllLevel()
        {
            ViewBag.GetAllLevel = "nav-active";
            return View();
        }
    }
}

CoStudyContentManagement/Controllers/LoggingController.cs
using Microsoft.AspNetCore.Mvc;

namespace CoStudyContentManagement.Controllers
{
    public class LoggingController : Controller
    {
        public IActionResult GetAll()
        {
            ViewBag.GetAll = "nav-active";
            return View();
        }

        [Route("detail/{id}")]
        public IActionResult Detail(string id)
        {
            ViewBag.Id = id;
            return View();
        }
    }
}

CoStudyContentManagement/Controllers/PostController.cs
using Microsoft.AspNetCore.Mvc;

namespace CoStudyContentManagement.Controllers
{
    /// <summary>
    /// Class PostController
    /// </summary>
    /// <seealso cref="Microsoft.AspNetCore.Mvc.Controller" />
    [Route("[controller]")]
    public class PostController : Controller
    {
        /// <summary>
        /// Gets all post.
        /// </summary>
        /// <returns></returns>
        [Route("all")]
        public IActionResult GetAllPost()
        {
            ViewBag.GetAllPost = "nav-active";
            return View();
        }

        /// <summary>
        /// Posts the detail.
        /// </summary>
        /// <returns></returns>
        [Route("detail")]
        public IActionResult PostDetail([FromQuery] string postId)
        {
            ViewBag.postId = postId;
            return View();
        }
    }
}

CoStudyContentManagement/Controllers/ReplyCommentController.cs
using Microsoft.AspNetCore.Mvc;

namespace CoStudyContentManagement.Controllers
{
    /// <summary>
    /// Class ReplyCommentController
    /// </summary>
    /// <seealso cref="Microsoft.AspNetCore.Mvc.Controller" />
    [Route("[controller]")]
    public class ReplyCommentController : Controller
    {
        /// <summary>
        /// Gets all.
        /// </summary>
        /// <returns></returns>
        [Route("all")]
        public IActionResult GetAll()
        {
            ViewBag.GetAllReply = "nav-active";
            return View();
        }

        /// <summary>
        /// Gets the by identifier.
        /// </summary>
        /// <param name="replyCommentId">The reply comment identifier.</param>
        /// <returns></returns>
        [Route("detail")]
        public IActionResult GetById([FromQuery]string replyCommentId)
        {
            ViewBag.replyCommentId = replyCommentId;
            return View();
        }

    }
}

CoStudyContentManagement/Controllers/ReportController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoStudyContentManagement.Controllers
{
    [Route("[controller]")]
    public class ReportController : Controller
    {
        [Route("all")]
        public IActionResult GetAllReport()
        {
            ViewBag.GetAllReport = "nav-active";
            return View();
        }
    }
}

CoStudyContentManagement/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoStudyContentManagement.Controllers
{
    /// <summary>
    /// Class UserController
    /// </summary>
    /// <seealso cref="Microsoft.AspNetCore.Mvc.Controller" />
    [Route("[controller]")]
    public class UserController : Controller
    {
        /// <summary>
        /// Alls the user.
        /// </summary>
        /// <returns></returns>
        [Route("all")]
        public IActionResult AllUser()
        {
            ViewBag.AllUser = "nav-active";
            return View();
        }

        /// <summary>
        /// Gets the user by identifier.
        /// </summary>
        /// <returns></returns>
        [Route("detail")]
        public IActionResult GetUserById([FromQuery] string email)
        {
            ViewBag.email = email;
            return View();
        }
    }
}

CoStudyContentManagement/Controllers/ViolenceWordController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoStudyContentManagement.Controllers
{
    [Route("[controller]")]
    public class ViolenceWordController : Controller
    {
        [Route("all")]
        public IActionResult GetAll()
        {
            ViewBag.AllViolenceWord = "nav-active";
            return View();
        }
    }
}

CoStudyContentManagement/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Logging";
}

CoStudyContentManagement/Views/Home/Login.cshtml
@using Microsoft.Extensions.Configuration

@{
    ViewData["Title"] = "Logging";
    Layout = null;
}
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="~/datatables/css/jquery.dataTables.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/datatables/js/jquery.dataTables.js"></script>
    <script src="https://cdn.datatables.net/plug-ins/1.10.22/dataRender/datetime.js"></script>
    <script src="https://editor.datatables.net/extensions/Editor/js/dataTables.editor.min.js"></script>
    <script src="https://cdn.datatables.net/plug-ins/1.10.22/api/processing().js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <link href="~/css/site.css" rel="stylesheet" />
    <script src="~/js/site.js"></script>

</head>

<style>
    /* Coded with love by Mutiullah Samim */

    /* BASIC */

    html {
        background-color: #56baed;
    }

    body {
        font-family: "Poppins", sans-serif;
        height: 100vh;
    }

    a {
        color: #92badd;
        display: inline-block;
        text-decoration: none;
        font-weight: 400;
    }

    h2 {
        text-align: center;
        font-size: 16px;
        font-weight: 600;
        text-transform: uppercase;
        display: inline-block;
        margin: 40px 8px 10px 8px;
        color: #cccccc;
    }



    /* STRUCTURE */

    .wrapper {
        display: flex;
        align-items: center;
        flex-direction: column;
        justify-content: center;
        width: 100%;
        min-height: 100%;
        padding: 20px;
    }

    #formContent {
        -webkit-border-radius: 10px 10px 10px 10px;
        border-radius: 10px 10px 10px 10px;
        background: #fff;
        padding: 30px;
        width: 90%;
        max-width: 450px;
        position: relative;
        padding: 0px;
        -webkit-box-shadow: 0 30px 60px 0 rgba(0,0,0,0.3);
        box-shadow: 0 30px 60px 0 rgba(0,0,0,0.3);
        text-align: center;
    }

    #formFooter {
        background-color: #f6f6f6;
        border-top: 1px solid #dce8f1;
        padding: 25px;
        text-align: center;
        -webkit-border-radius: 0 0 10px 10px;
        border-radius: 0 0 10px 10px;
    }



    /* TABS */

    h2.inactive {
        color: #cccccc;
    }

    h2.active {
        color: #0d0d0d;
        border-bottom: 2px solid #5fbae9;
    }



    /* FORM TYPOGRAPHY*/

    input[type=button], input[type=submit], input[type=reset], input[type=password]  button {
        background-color: #56baed;
        border: none;
        color: white;
        padding: 15px 80px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        text-transform: uppercase;
        font-size: 13px;
        -webkit-box-shadow: 0 10px 30px 0 rgba(95,186,233,0.4);
        box-shadow: 0 10px 30px 0 rgba(95,186,233,0.4);
        -webkit-border-radius: 5px 5px 5px 5px;
        border-radius: 5px 5px 5px 5px;
        margin: 5px 20px 40px 20px;
        -webkit-transition: all 0.3s ease-in-out;
        -moz-transition: all 0.3s ease-in-out;
        -ms-transition: all 0.3s ease-in-out;
        -o-transition: all 0.3s ease-in-out;
        transition: all 0.3s ease-in-out;
    }

        input[type=button]:hover, input[type=submit]:hover, input[type=reset], input[type=password], button:hover {
            background-color: #39ace7;
        }

            input[type=button]:active, input[type=submit]:active, input[type=reset]:active, input[type=password]:active, button:active {
                -moz-transform: scale(0.95);
                -webkit-transform: scale(0.95);
                -o-transform: scale(0.95);
                -ms-transform: scale(0.95);
                transform: scale(0.95);
            }

    input[type=text], input[type=password] {
        background-color: #f6f6f6;
        border: none;
        color: #0d0d0d;
        padding: 15px 32px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 5px;
        width: 85%;
        border: 2px solid #f6f6f6;
        -webkit-transition: all 0.5s ease-in-out;
        -moz-transition: all 0.5s ease-in-out;
        -ms-transition: all 0.5s ease-in-out;
        -o-transition: all 0.5s ease-in-out;
        transition: all 0.5s ease-in-out;
        -webkit-border-radius: 5px 5px 5px 5px;
        border-radius: 5px 5px 5px 5px;
    }

        input[type=text]:focus, input[type=password]:focus {
            background-color: #fff;
            border-bottom: 2px solid #5fbae9;
        }

        input[type=text]:placeholder {
            color: #cccccc;
        }



    /* ANIMATIONS */

    /* Simple CSS3 Fade-in-down Animation */
    .fadeInDown {
        -webkit-animation-name: fadeInDown;
        animation-name: fadeInDown;
        -webkit-animation-duration: 1s;
        animation-duration: 1s;
        -webkit-animation-fill-mode: both;
        animation-fill-mode: both;
    }

    @@-webkit-keyframes fadeInDown {
        0% {
            opacity: 0;
            -webkit-transform: translate3d(0, -100%, 0);
            transform: translate3d(0, -100%, 0);
        }

        100% {
            opacity: 1;
            -webkit-transform: none;
            transform: none;
        }
    }

    @@keyframes fadeInDown {
        0% {
            opacity: 0;
            -webkit-transform: translate3d(0, -100%, 0);
            transform: translate3d(0, -100%, 0);
        }

        100% {
            opacity: 1;
            -webkit-transform: none;
            transform: none;
        }
    }

    /* Simple CSS3 Fade-in Animation */
    @@-webkit-keyframes fadeIn {
        from {
            opacity: 0;
        }

        to {
            opacity: 1;
        }
    }

    @@-moz-keyframes fadeIn {
        from {
            opacity: 0;
        }

        to {
            opacity: 1;
        }
    }

    @@keyframes fadeIn {
        from {
            opacity: 0;
        }

        to {
            opacity: 1;
        }
    }

    .fadeIn {
        opacity: 0;
        -webkit-animation: fadeIn ease-in 1;
        -moz-animation: fadeIn ease-in 1;
        animation: fadeIn ease-in 1;
        -webkit-animation-fill-mode: forwards;
        -moz-animation-fill-mode: forwards;
        animation-fill-mode: forwards;
        -webkit-animation-duration: 1s;
        -moz-animation-duration: 1s;
        animation-duration: 1s;
    }

        .fadeIn.first {
            -webkit-animation-delay: 0.4s;
            -moz-animation-delay: 0.4s;
            animation-delay: 0.4s;
        }

        .fadeIn.second {
            -webkit-animation-delay: 0.6s;
            -moz-animation-delay: 0.6s;
            animation-delay: 0.6s;
        }

        .fadeIn.third {
            -webkit-animation-delay: 0.8s;
            -moz-animation-delay: 0.8s;
            animation-delay: 0.8s;
        }

        .fadeIn.fourth {
            -webkit-animation-delay: 1s;
            -moz-animation-delay: 1s;
            animation-delay: 1s;
        }

    /* Simple CSS3 Fade-in Animation */
    .underlineHover:after {
        display: block;
        left: 0;
        bottom: -10px;
        width: 0;
        height: 2px;
        background-color: #56baed;
        content: "";
        transition: width 0.2s;
    }

    .underlineHover:hover {
        color: #0d0d0d;
    }

        .underlineHover:hover:after {
            width: 100%;
        }



    /* OTHERS */

    *:focus {
        outline: none;
    }

    #icon {
        width: 60%;
    }
</style>

<div class="wrapper fadeInDown">
    <div id="formContent">
        <!-- Tabs Titles -->
        <!-- Icon -->
        <div class="fadeIn first">
            <h3 class="pt-4">Đăng nhập </h3>
        </div>

        <!-- Login Form -->
        <div>
            <input type="text" id="username" class="fadeIn second" autocomplete="" placeholder="Tên tài khoản">
            <input type="password" id="password" class="fadeIn third" autocomplete="" placeholder="Mật khẩu">
            <p style="color:red; font-size:12px;" id="errorLogin"></p>

            <button class="btn btn-info fadeIn fourth mb-3" id="btn_login" > Đăng nhập</button>
        </div>


    </div>
</div>

@inject IConfiguration Configuration
@{
    string apiUrl = Configuration["api_url"];
    string clientUrl = Configuration["client_url"];
}
<script>

    const API_URL = "@apiUrl";
    const CLIENT_URL = "@clientUrl";

    $(document).ready(

        function () {
            $("#btn_login").click(
                function () {
                    $.ajax({
                        type: 'POST',
                        url: API_URL + 'Accounts/login',
                        data: JSON.stringify({
                            email: $("#username").val(),
                            password: $("#password").val()
                        }),
                        contentType: "application/json",
                        dataType: "json",
                        success: function (response) {
                            console.log(response.result.jwtToken);
                            setCookie("accessToken", response.result.jwtToken, 1);
                            window.location.href = CLIENT_URL + 'User/all';
                        },
                        error: function (response) {
                            console.log(response);
                            $("#errorLogin").html('Tài khoản hoặc mật khẩu không đúng');
                        }
                    });
                }
            );
        }
    );

</script>

CoStudyContentManagement/Views/Logging/Detail.cshtml
@{
    ViewData["Title"] = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Detail</h1>

<h1> @ViewBag.id</h1>

<h2 id="url"> </h2>
<h2 id="path"></h2>
<h2 id="time_elapsed"></h2>
<script>
    $(document).ready(
        function () {
            getLoggingByDetail();
        }
    );

    function getLoggingByDetail() {

        $.ajax({
            type: 'GET',
            url: API_URL + 'api/Logging/' + '@ViewBag.id.ToString()',
            success: function (response) {
                console.log(url);
                $("#url").text(response.result.location);
                $("#path").text(response.result.requestPath);
                $("#time_elapsed").text(response.result.timeElapsed);
            },
            error: function (response) {
                console.log(response);
                console.log(url);
            }
        }
        );
    }
</script>

CoStudyContentManagement/Views/ReplyComment/ConfirmModal.cshtml
<div class="modal fade" style="z-index: 1000000" id="deleteConfirmModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-body">
                Bạn có xác nhận xóa bình luận này?
                <input type="hidden" id="id_to_delete" />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Không</button>
                <button type="button" id="btnDelete" class="btn btn-primary" data-dismiss="modal">Xác nhận</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" style="z-index: 1000000" id="blockConfirmModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-body">
                Bạn có xác nhận chặn bình luận này?
                <input type="hidden" id="id_to_block" />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Không</button>
                <button type="button" id="btnBlock" class="btn btn-primary" data-dismiss="modal">Xác nhận</button>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" style="z-index: 1000000" id="activeConfirmModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-body">
                Bạn có xác nhận mở bình luận này?
                <input type="hidden" id="id_to_active" />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Không</button>
                <button type="button" id="btnActive" class="btn btn-primary" data-dismiss="modal">Xác nhận</button>
            </div>
        </div>
    </div>
</div>

CoStudyContentManagement/Views/Shared/_Layout.cshtml
@using Microsoft.Extensions.Configuration
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="~/datatables/css/jquery.dataTables.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/datatables/js/jquery.dataTables.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.7.1/js/dataTables.buttons.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.7.1/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.7.1/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/plug-ins/1.10.22/dataRender/datetime.js"></script>
    <script src="https://editor.datatables.net/extensions/Editor/js/dataTables.editor.min.js"></script>
    <script src="https://cdn.datatables.net/plug-ins/1.10.22/api/processing().js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <link href="~/css/site.css" rel="stylesheet" />

    @inject IConfiguration Configuration
    @{
        string apiUrl = Configuration["api_url"];
        string clientUrl = Configuration["client_url"];
    }
    <script>
        const API_URL = "@apiUrl";
        const CLIENT_URL = "@clientUrl";
    </script>
    <script src="~/js/components/toast.js"></script>
    <script src="~/js/components/Button.js"></script>
    <script src="~/js/components/StatusButton.js"></script>
    <script src="~/js/site.js"></script>
    <script>
        $(document).ready(function () {
            $('input').attr('maxlength', 15);
           
        });
    </script>
    <style>
        .btn {
            cursor: pointer;
        }
    </style>
</head>
<body style="background-color: #E5E5E5">
    <header>
        <nav style="background-color:#2A8383 !important" class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-uppercase" asp-area="" asp-controller="Home" asp-action="Index" style="color:white">CoStudy - Hệ thống quản lý tài nguyên </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex">
                    <ul class="navbar-nav flex-grow-1  justify-content-end">
                        <li class="nav-item">
                            <button class="btn nav-link text-light border text-uppercase " id="logout">Đăng xuất </button>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container-fluid row">
        <div class="col-2 row d-flex justify-content-center" id="left-nav">
            <div class="col-10">
                <a asp-controller="Logging" asp-action="GetAll" class="btn btn-block btn-outline-dark text-left  @ViewBag.GetAll">API</a>
                <a asp-controller="User" asp-action="AllUser" class="btn btn-block btn-outline-dark text-left @ViewBag.AllUser">Quản lý tài khoản</a>
                <a asp-controller="Post" asp-action="GetAllPost" class="btn btn-block btn-outline-dark text-left @ViewBag.GetAllPost">Quản lý bài viết</a>
                <a asp-controller="Comment" asp-action="GetAll" class="btn btn-block btn-outline-dark text-left @ViewBag.GetAllComment ">Quản lý bình luận</a>
                <a asp-controller="Report" asp-action="GetAllReport" class="btn btn-block btn-outline-dark text-left @ViewBag.GetAllReport">Quản lý báo cáo</a>
                <a asp-controller="ReplyComment" asp-action="GetAll" class="btn btn-block btn-outline-dark text-left @ViewBag.GetAllReply">Quản lý trả lời</a>
                <a asp-controller="Field" asp-action="GetAllField" class="btn btn-block btn-outline-dark text-left @ViewBag.GetAllField">Danh mục lĩnh vực</a>
                <a asp-controller="Level" asp-action="GetAllLevel" class="btn btn-block btn-outline-dark text-left @ViewBag.GetAllLevel">Danh mục cấp độ</a>
                <a asp-controller="FieldGroup" asp-action="GetAll" class="btn btn-block btn-outline-dark text-left @ViewBag.GetAllFieldGroup">Nhóm lĩnh vực</a>
                <a asp-controller="ViolenceWord" asp-action="GetAll" class="btn btn-block btn-outline-dark text-left @ViewBag.AllViolenceWord">Từ ngữ vi phạm</a>

            </div>
        </div>
        <main role="main" class="col-10  main-border p-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted pt-2 ">
        <div class="container">
            &copy; 2021 - CoStudyContentManagement - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <div class="modal"><!-- Place at bottom of page --></div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        $body = $("body");
        $(document).on({
            ajaxStart: function () { $('[id*="Table_wrapper"]').addClass("loading"); },
            ajaxStop: function () { $('[id*="Table_wrapper"]').removeClass("loading"); }
        });
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>